#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 4
paginate_path: "/blog/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /projects/:slug
  videos:
    output: true
    permalink: /videos/:slug
  services:
    output: true
    permalink: /services/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "services"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "services"

sass:
  sass_dir: _sass
  style: compressed