version: '3.8'

services:
  jekyll:
    container_name: jekyll
    image: jekyll/jekyll
    command: jekyll build
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "9999:80"
    volumes:
      - ./_site:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jekyll
