#-------------------------------
# Site Settings
title: Richard Vogel - Technologie gegen Finanzkriminalität
description: Cloud-Architekt und Java-Entwickler mit 12 Jahren Erfahrung. Technologie-Experte im Kampf gegen Finanzkriminalität sowie für das Gesundheitswesen.
color_scheme: auto # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "/images/hintergrund-unsplash.jpg" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Services'
      url: '/services/'
    - title: 'Branchen'
      url: '/projects/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Author Settings
author:
  author_name: Richard Vogel
  author_role: Ihr Experte für Technologie im Bereich Anti-Finanzkriminalität und Gesundheitswesen
  author_bio: "Als erfahrener Cloud-Architekt und Java-Entwickler mit über 12 Jahren Erfahrung in der Softwareentwicklung - 9 davon im Banken und Versicherungsumfeld - unterstütze ich Ihr Unternehmen dabei, effektive Lösungen zu entwickeln und zu integrieren. Meine Expertise liegt in der Implementierung maßgeschneiderter Technologien im Bereich der <strong>Bekämpfung von Finanzkriminalität</strong> und der <strong>Digitalisierung des Gesundheitswesens</strong>.<p><p>Als zertifizierer Softwarearchitekt (iSAQB CPSA-A und CPSA-F) sowie AWS Certified Solutions Architect helfe ich Ihnen, Systeme zu schaffen, die sowohl Compliance-Anforderungen erfüllen als auch höchste Effizienz und Skalierbarkeit bieten.<p><p><strong>Kontaktieren Sie mich um</strong><p><ul><li>Ihren <strong>Legacy-Monolithen</strong> fit für die Cloud zu machen.</li><li>Ihre <strong>KYC und AML</strong> Lösungen in Ihre Infrastruktur zu integrieren.</li><li>Ihren Meldeprozess an die <strong>FIU mit goAML XML</strong> Dateien zu automatisieren.</li><li>Einen Im Rahmen von <strong>PSD3</strong> einen <strong>IBAN-Name-Check</strong> zu implementieren.</li><li>Ihre <strong>Software-Architektur</strong> zu bewerten und verbessern.</li></ul><p><p>Ich freue mich auf Ihre Anfrage"
  author_avatar: '/images/profile.png'
  cta_button_text: Kontaktieren
  cta_button_link: '/contact/'


#-------------------------------
# Projects Settings
projects_settings:
  enable: true
  projects_title: Branchen
  projects_description:


#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Testimonials
  testimonials_description:

testimonial_items:
  - name: "Albert Flores"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    content : "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  - name: "Wade Warren"
    image: "/images/client-2.jpg"
    designation: "DevOps Engineer"
    content : "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  - name: "Jenny Wilson"
    image: "/images/client-3.jpg"
    designation: "Systems Analyst"
    content : "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."


#-------------------------------
# Blog Section
blog_settings:
  enable: false
  blog_title: Blog
  blog_description:


#-------------------------------
# Videos Settings
videos_settings:
  enable: false
  videos_title: Videos
  videos_description:


#-------------------------------
# Services Section
services_settings:
  enable: true
  services_title: Services
  services_description:


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Me # Add your button text


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/richard-vogel-software/"}
- {icon: "fa-brands fa-xing", name: "Xing", link: "https://www.xing.com/profile/Richard_Vogel8"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: xvgoagra # Add your form_id
  description: Bei Interesse zögern Sie bitte nicht, mich zu kontaktieren – ich freue mich auf Ihre Anfrage!

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: G-J1V5W5LV4T